# Generated by Django 3.2.6 on 2021-09-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='done',
            field=models.CharField(choices=[('fazendo', 'Fazendo'), ('feita', 'Feita')], max_length=7),
        ),
    ]
