# Generated by Django 3.2.6 on 2021-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_diario_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
